/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (vigilante-8-)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x800116D4u
#define func_800116D4 BootEntry  /* alias */
